import { defineRouteMiddleware } from "@astrojs/starlight/route-data";
import type { StarlightRouteData } from "@astrojs/starlight/route-data";

import { repoRelativePath, titleCase } from "../docs-source";

/**
 * `@astrojs/starlight/route-data` exports only `StarlightRouteData`, so the
 * entry type is projected out of it rather than imported. Doing it this way
 * also means the sidebar walker below cannot drift from whatever shape a future
 * Starlight release gives these objects -- it stops compiling instead.
 */
type SidebarEntry = StarlightRouteData["sidebar"][number];

/** Where a reader is sent when they click "Edit page". */
const EDIT_BASE = "https://github.com/yashau/prick/edit/main/";

/** A label that is still a raw directory name: `using-secrets`, `getting-started`. */
const SLUG_LABEL = /^[a-z0-9]+(?:[-_][a-z0-9]+)*$/;

/**
 * Route data fixes that cannot be expressed in `astro.config.ts`.
 *
 * All three below are consequences of loading content from outside
 * `src/content/docs/`, or of Starlight defaults that read badly for this
 * specific site. None of them require editing a file under `docs/`, which is
 * deliberate: that directory belongs to a different workstream.
 */
export const onRequest = defineRouteMiddleware((context) => {
  const route = context.locals.starlightRoute;

  fixEditUrl(route);
  fixAutogeneratedGroupLabels(route.sidebar);
  fixDuplicatedTitle(route);
});

/**
 * 1. Point "Edit page" at the real file.
 *
 * Starlight's `editLink.baseUrl` option builds the URL as
 * `baseUrl + entry.filePath` (see `utils/routing/data.ts:getEditUrl`). That is
 * right when content sits in `src/content/docs/`, and wrong here: our
 * `filePath` values start with `../../docs/`, so concatenating them onto a
 * GitHub URL produces a link that either 404s or -- worse, because `new URL()`
 * silently normalises `..` segments -- quietly resolves to a plausible-looking
 * path in the wrong part of the repository.
 *
 * Rather than tuning `baseUrl` until the dot-segment arithmetic happens to come
 * out right (a trick that breaks the moment this package moves), the URL is
 * computed from the file's real position in the repository. Route middleware is
 * Starlight's supported extension point for exactly this.
 *
 * `editLink.baseUrl` is therefore deliberately NOT set in `astro.config.ts`:
 * setting both would leave two mechanisms racing to define the same link.
 */
function fixEditUrl(route: StarlightRouteData): void {
  // A page may switch editing off with `editUrl: false` in its frontmatter, or
  // redirect it with a string. Respect both.
  if (route.entry.data.editUrl === false) return;
  if (typeof route.entry.data.editUrl === "string") return;

  const relative = repoRelativePath(route.entry.filePath);
  route.editUrl = relative ? new URL(EDIT_BASE + relative) : undefined;
}

/**
 * 2. Make nested autogenerated group labels readable.
 *
 * Starlight labels an autogenerated subgroup with the raw directory name
 * (`utils/navigation.ts:groupFromDir` sets `label: dirName`), and there is no
 * frontmatter or config option to override it -- not even an `index.md` inside
 * the directory. So `docs/guides/using-secrets/` renders as "using-secrets",
 * sitting directly beneath a hand-written "Getting Started".
 *
 * Title-casing it here keeps the sidebar fully autogenerated -- a new
 * subdirectory still needs no configuration -- while not looking like a bug.
 *
 * Only groups that Starlight generated (`autogenerate` is present) and whose
 * label still looks like a slug are touched, so an explicitly configured label
 * can never be rewritten.
 */
function fixAutogeneratedGroupLabels(entries: SidebarEntry[]): void {
  for (const entry of entries) {
    if (entry.type !== "group") continue;
    if ("autogenerate" in entry && SLUG_LABEL.test(entry.label)) {
      entry.label = titleCase(entry.label);
    }
    fixAutogeneratedGroupLabels(entry.entries);
  }
}

/**
 * 3. Stop a page announcing itself twice.
 *
 * Starlight composes every `<title>` as `${page title} | ${site title}`
 * (`utils/head.ts`), so a page whose title equals the site's reads "X | X" in
 * the browser tab.
 *
 * Nothing collides while the site is called "Prick Documentation" -- the
 * documentation root is titled "prick", which no longer matches. The guard
 * stays because it is structural rather than a patch for one page: it costs a
 * single string compare, and it holds whichever of the two names changes next.
 * It has to live on this side either way, since `docs/index.md` is not ours to
 * edit.
 */
function fixDuplicatedTitle(route: StarlightRouteData): void {
  for (const tag of route.head) {
    if (tag.tag !== "title" || !tag.content) continue;
    const [left, right] = tag.content.split(" | ");
    if (left && left === right) tag.content = left;
  }
}
