// `Env`, `CfProperties` and `ExecutionContext` come from
// `worker-configuration.d.ts`, generated by `wrangler types` and pulled in via
// the `files` entry in tsconfig.json rather than a triple-slash reference.

// `import type`, so nothing here survives into emitted JavaScript and the
// server-only import guard has nothing to object to: a `.d.ts` is erased
// entirely and is not part of the module graph SvelteKit walks.
import type { Actor, CoreContext } from "$lib/server/core";

declare global {
  namespace App {
    interface Error {
      code?: string;
      message: string;
      /** Echoed `X-Request-Id`, so an error toast is traceable to an audit row. */
      requestId?: string;
      hint?: string;
    }

    /**
     * What `hooks.server.ts` resolved before any load ran.
     *
     * BOTH FIELDS ARE NON-OPTIONAL, and that is the point. The hook either
     * builds a context or refuses the request, so a load never has to decide
     * what to do without one -- there is no `locals.ctx?` to be optional-chained
     * past, and therefore no path where a load silently runs unauthenticated.
     */
    interface Locals {
      /**
       * The request's `CoreContext`: database, verified actor, request id,
       * clock, parsed config and key ring.
       *
       * THE OBJECT IDENTITY MATTERS. `resolveAuthorization` memoises the
       * authorization snapshot in a `WeakMap` keyed by this exact reference, so
       * a load that fans out over several `core.*` calls resolves grants once.
       * Never build a second context for one request.
       */
      ctx: CoreContext;
      /**
       * `ctx.actor`, hoisted for the loads that only need to know who is
       * looking. The same object, not a copy.
       */
      actor: Actor;
    }

    interface PageData {}

    interface PageState {}

    /**
     * Supplied by the Workers runtime in production and by the
     * adapter-cloudflare `platformProxy` (miniflare) during `vite dev`, so the
     * same code path runs in both.
     */
    interface Platform {
      env: Env;
      cf: CfProperties;
      ctx: ExecutionContext;
    }
  }
}

export {};
