// `Env`, `CfProperties` and `ExecutionContext` come from
// `worker-configuration.d.ts`, generated by `wrangler types` and pulled in via
// the `files` entry in tsconfig.json rather than a triple-slash reference.

declare global {
  namespace App {
    interface Error {
      code?: string;
      message: string;
      /** Echoed `X-Request-Id`, so an error toast is traceable to an audit row. */
      requestId?: string;
      hint?: string;
    }

    // Empty on purpose. `Locals` is populated in build order step 10/11, when
    // hooks.server.ts starts attaching the verified actor to the event.
    interface Locals {}

    interface PageData {}

    interface PageState {}

    /**
     * Supplied by the Workers runtime in production and by the
     * adapter-cloudflare `platformProxy` (miniflare) during `vite dev`, so the
     * same code path runs in both.
     */
    interface Platform {
      env: Env;
      cf: CfProperties;
      ctx: ExecutionContext;
    }
  }
}

export {};
