import { defineConfig } from "vite-plus";

/**
 * The ROOT Vite+ config. It configures the toolchain, not a build.
 *
 * WHY THIS FILE HAS TO EXIST -- and it is not a style preference:
 *
 * `mise run fmt:check:js` and `lint:js` invoke `vp` from the repository root.
 * Without a root config, `vp` walks the pnpm workspace looking for one and
 * loads `packages/app/vite.config.ts` with the ROOT as its working directory.
 * That config registers SvelteKit's plugin, which resolves `src/app.html`
 * relative to the cwd, does not find it, and aborts:
 *
 *     Failed to load config in packages/app: Error: src\app.html does not exist
 *
 * So the whole formatting and linting gate failed before it had looked at a
 * single file. A root config short-circuits that discovery. `packages/app`
 * keeps its own `vite.config.ts` for the actual build; the two do not overlap.
 *
 * QUOTE STYLE: Oxfmt's default (double) is kept deliberately. Every TypeScript
 * file in `packages/app`, `packages/shared` and `e2e` is already written that
 * way, so switching the default would rewrite the entire tree. `scripts/**` is
 * single-quoted Node ESM and is given an override rather than being rewritten,
 * because those files are owned elsewhere and their style is internally
 * consistent.
 *
 * PRINT WIDTH: 100, matching `max_line_length` in `.editorconfig`. Stated
 * rather than inherited -- `.editorconfig` governs editors, this governs the
 * formatter, and the two silently disagreeing is exactly the failure mode a
 * single formatter was chosen to remove.
 */
export default defineConfig({
  fmt: {
    printWidth: 100,
    semi: true,
    singleQuote: false,
    ignorePatterns: [
      "**/dist/**",
      "**/.svelte-kit/**",
      "**/node_modules/**",
      "target/**",
      // Generated by `wrangler types`; regenerated wholesale by `cf-typegen`.
      "packages/app/worker-configuration.d.ts",
      // Generated by drizzle-kit. Reformatting them would make every future
      // `db:generate` produce a spurious diff.
      "packages/app/drizzle/**",
      // Generated by `node scripts/openapi.mjs write` from the Hono router, and
      // compared byte-for-byte by `... check`. The generator sorts keys and
      // emits two-space JSON precisely so that a route change is a readable
      // diff; letting a second formatter rewrite it afterwards would make the
      // freshness gate fail on whitespace the moment anyone ran `vp fmt`.
      "docs/openapi.json",
    ],
    overrides: [
      {
        // Node ESM repo scripts, single-quoted throughout.
        files: ["scripts/**"],
        options: {
          singleQuote: true,
        },
      },
    ],
  },
});
