import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";

import { SITE_TAGLINE, SITE_TITLE, sidebarGroups, warnIfDocsMissing } from "./docs-source";

warnIfDocsMissing();

export default defineConfig({
  // The public docs hostname. Used for canonical URLs, the sitemap and Open
  // Graph tags; change it together with the route in `wrangler.jsonc`.
  site: "https://docs.prick.dev",

  // ---------------------------------------------------------------------------
  // Fully static. There is no server.
  //
  // This site has no database, no authentication and no secrets, so there is
  // nothing for a Worker to do that the assets runtime cannot do faster. That
  // is also why `@astrojs/cloudflare` is NOT a dependency: an SSR adapter would
  // buy nothing here and would add a runtime to keep patched.
  // ---------------------------------------------------------------------------
  output: "static",

  // Trailing-slash-free URLs, matching `html_handling: auto-trailing-slash` on
  // the assets runtime.
  build: { format: "directory" },

  // ---------------------------------------------------------------------------
  // `security.csp` is deliberately LEFT OFF. This was tried, measured, and
  // rejected -- do not switch it on without repeating the measurement.
  //
  // Astro's CSP support hashes the inline <script> and <style> ELEMENTS it
  // emits and ships the policy as a <meta> tag. Enabling it here produced
  // `style-src 'self' <2 hashes>` -- and a single built page carries 299 inline
  // `style="..."` ATTRIBUTES, from Starlight's own components (`--sl-icon-size`
  // on every icon) and from Expressive Code's syntax highlighting.
  //
  // Hashes do not authorise style attributes; only `'unsafe-inline'` or
  // `'unsafe-hashes'` does, and both are ignored once a hash-source is present
  // in the same directive. So the generated policy blocks all 299 of them. That
  // is not a cosmetic problem: several are `style="display: none;"`, and a
  // blocked `display: none` fails OPEN -- collapsed menus and the search modal
  // render permanently visible.
  //
  // Astro says as much itself at build time:
  //   "Shiki syntax highlighting uses inline styles that are not compatible
  //    with Content Security Policy (CSP)."
  //
  // The policy therefore lives entirely in `public/_headers`, where it is a
  // real header rather than a <meta> tag -- which it has to be anyway, because
  // `frame-ancestors` is specified to be ignored in meta CSP.
  // ---------------------------------------------------------------------------

  integrations: [
    starlight({
      title: SITE_TITLE,
      description: `${SITE_TAGLINE} -- a self-hosted secrets manager that runs on one Cloudflare Worker and a D1 database.`,

      // Plain and legible; no logo asset to keep in sync.
      tagline: SITE_TAGLINE,

      social: [{ icon: "github", label: "GitHub", href: "https://github.com/yashau/prick" }],

      // Pagefind. Starlight builds the index as part of a static build and
      // serves it from `/pagefind/`; it is stated explicitly here because it is
      // a feature this site is required to have, not an implementation detail
      // that may be silently defaulted away.
      pagefind: true,

      // The dark/light toggle is Starlight's default and is left on. Stated for
      // the same reason.
      // (`defaultProps.themeToggle` does not exist; the control is unconditional.)

      // Edit links are built in `src/routeData.ts`, NOT here. See that file for
      // why `editLink.baseUrl` cannot be used when content is loaded from
      // outside `src/content/docs/`.
      routeMiddleware: "./src/routeData.ts",

      // Autogenerated from the directory structure, in a fixed group order.
      // Adding a page to an existing directory requires no change here.
      sidebar: sidebarGroups(),

      // Starlight ships a 404 route out of the box. Overriding it would mean
      // adding a file to `docs/`, which belongs to another workstream, so the
      // built-in page stands. `wrangler.jsonc` points `not_found_handling` at
      // the `/404.html` it produces.
    }),
  ],
});
