/**
 * Where the documentation Markdown lives, and nothing else.
 *
 * =============================================================================
 * THE CONTENT IS NOT IN THIS PACKAGE.
 *
 * Every Markdown file rendered by this site lives in the repository-root
 * `docs/` directory. This package is a renderer, not a copy of the docs.
 *
 * It is read IN PLACE by Astro's content-layer `glob()` loader (see
 * `src/content.config.ts`). There is deliberately no symlink and no prebuild
 * copy step:
 *
 *   - a copy step means two sources of truth, and on Windows a stale `dist/`
 *     from an aborted build is indistinguishable from a fresh one;
 *   - symlinks require Developer Mode or an elevated shell on Windows 11 and
 *     do not survive a plain `git clone` for every contributor.
 *
 * The loader reads the originals, so "the docs" has exactly one meaning.
 * =============================================================================
 */
import { existsSync, readdirSync } from "node:fs";
import path from "node:path";

/**
 * Path to the docs directory, relative to this Astro project's root.
 *
 * This exact string is what `glob({ base })` is given, and Astro resolves it
 * against `config.root`. It is also the prefix that appears in every
 * `entry.filePath`, which is why the sidebar and the edit links below are
 * derived from it rather than hard-coding the same relative path three times.
 */
export const DOCS_BASE = "../../docs";

/**
 * Absolute path to the same directory.
 *
 * Resolved against `process.cwd()` on purpose: Astro's own `root` defaults to
 * the working directory, so this resolves identically to the way the loader
 * resolves `DOCS_BASE`. If someone invokes Astro from an unexpected directory,
 * both resolve wrongly together and the "docs directory not found" warning
 * below fires -- rather than the sidebar and the content silently disagreeing.
 */
export const DOCS_DIR = path.resolve(process.cwd(), DOCS_BASE);

/**
 * File extensions the loader picks up. Mirrors the list Starlight's own
 * `docsLoader()` uses so that switching back to it later changes nothing.
 */
export const DOCS_EXTENSIONS = ["markdown", "mdown", "mkdn", "mkd", "mdwn", "md", "mdx"];

/**
 * Glob pattern for the loader.
 *
 * `[^_]*` is not decoration: it reproduces Starlight's convention that a
 * leading underscore marks a partial that must not become a page.
 */
export const DOCS_PATTERN = `**/[^_]*.{${DOCS_EXTENSIONS.join(",")}}`;

/**
 * Sidebar groups, in the order they must read.
 *
 * Each entry is AUTOGENERATED from its directory, so a new Markdown file
 * dropped into `docs/guides/` appears in the sidebar with no change to this
 * file. Only a brand-new top-level directory needs attention -- and even then
 * it is picked up automatically and appended (see `sidebarGroups()`), it just
 * gets a mechanically title-cased label instead of a curated one.
 */
const GROUP_ORDER = [
  { directory: "getting-started", label: "Getting Started" },
  { directory: "guides", label: "Guides" },
  { directory: "examples", label: "Examples" },
  { directory: "reference", label: "Reference" },
  { directory: "architecture", label: "Architecture" },
  { directory: "contributing", label: "Contributing" },
] as const;

/**
 * The site's own name, rendered as text in the header beside the mark.
 *
 * Starlight composes every `<title>` as `${page title} | ${SITE_TITLE}`, so this
 * is what a browser tab, a bookmark and a search result carry. "prick" alone was
 * ambiguous there -- it is the name of the product, not of this site, and a tab
 * reading `prick` says nothing about being documentation.
 */
export const SITE_TITLE = "Prick Documentation";

/** Expansion of the acronym, used as the tagline and the meta description. */
export const SITE_TAGLINE = "Portable Runtime Injection of Cloudflare (stored) Keys";

/**
 * Words that are acronyms rather than ordinary nouns, keyed by their lowercase
 * form.
 *
 * Without this, `docs/reference/cli/` renders in the sidebar as "Cli", which
 * reads as a typo rather than as the name of the thing. Mechanical title-casing
 * has no way to know the difference, so the exceptions are listed.
 */
const ACRONYMS = new Map<string, string>([
  ["api", "API"],
  ["cli", "CLI"],
]);

/** Turn `getting-started` into `Getting Started`, and `cli` into `CLI`. */
export function titleCase(dirName: string): string {
  return dirName
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => ACRONYMS.get(word.toLowerCase()) ?? word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** Top-level directories that currently exist under `docs/`. */
function existingDocsDirectories(): string[] {
  if (!existsSync(DOCS_DIR)) return [];
  return readdirSync(DOCS_DIR, { withFileTypes: true })
    .filter(
      (entry) => entry.isDirectory() && !entry.name.startsWith("_") && !entry.name.startsWith("."),
    )
    .map((entry) => entry.name)
    .sort();
}

/**
 * Build the Starlight sidebar.
 *
 * Tolerance is the point. A directory in `GROUP_ORDER` that does not exist yet
 * is skipped rather than rendering an empty group, and a directory that exists
 * but is not in `GROUP_ORDER` is appended alphabetically rather than vanishing.
 * The docs are written by a separate workstream; this file must never be the
 * reason a build fails.
 *
 * Note the `${DOCS_BASE}/` prefix on `directory`. Starlight matches an
 * autogenerate directory against `entry.filePath` with its own content
 * directory stripped off. Because these entries are loaded from outside
 * `src/content/docs/`, nothing is stripped, and the paths Starlight compares
 * against still carry the `../../docs/` prefix. Prefixing here is what makes
 * the match succeed; it is not a workaround for a bug.
 */
export function sidebarGroups() {
  const present = new Set(existingDocsDirectories());
  const known = new Set<string>(GROUP_ORDER.map((group) => group.directory));

  const ordered = GROUP_ORDER.filter((group) => present.has(group.directory));

  const extras = [...present]
    .filter((dirName) => !known.has(dirName))
    .map((dirName) => ({ directory: dirName, label: titleCase(dirName) }));

  // Shape note: `{ label, autogenerate }` on the same object was REMOVED in
  // Starlight 0.39.0. A labelled group now takes an `items` array, and the
  // autogenerate config goes inside it. Getting this wrong is a hard config
  // error at build time, not a silent misrender.
  return [...ordered, ...extras].map(({ directory, label }) => ({
    label,
    items: [{ autogenerate: { directory: `${DOCS_BASE}/${directory}` } }],
  }));
}

/**
 * Turn an `entry.filePath` into its path relative to the repository root, for
 * building an edit-on-GitHub URL.
 *
 * Returns `undefined` when the path is not one of ours, so a page contributed
 * by a plugin never gets a link to a file that does not exist.
 */
export function repoRelativePath(filePath: string | undefined): string | undefined {
  if (!filePath) return undefined;
  const normalised = filePath.split(path.sep).join("/");
  const prefix = `${DOCS_BASE}/`;
  return normalised.startsWith(prefix) ? `docs/${normalised.slice(prefix.length)}` : undefined;
}

/** Warn once, loudly, if the content directory is missing. */
export function warnIfDocsMissing(): void {
  if (existsSync(DOCS_DIR)) return;
  console.warn(
    `[docs] The content directory ${DOCS_DIR} does not exist. ` +
      `The site will build, but it will contain no pages beyond the 404.`,
  );
}
